name: rinha-zig

services:
  haproxy:
    image: haproxy:3.0-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"
    networks:
      - backend

  api1:
    image: michaelbullet/bulletonrails-zig:v11
    hostname: api1
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - backend

  api2:
    image: michaelbullet/bulletonrails-zig:v11
    hostname: api2
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "160MB"
    networks:
      - backend

networks:
  backend:
    driver: bridge
